name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.10'
            
            - name: Docker BuildX
              uses: docker/setup-buildx-action@v1

            - name: Build image
              run: docker build -t workout_app .
            
            - name: Run Unit Tests
              run: |
                docker run workout_app pytest tests/unit/

            - name: Run Integration Tests
              run: |
                docker run workout_app pytest tests/integration/
            
            